config/routes.rb
Rails.application.routes.draw do

  get 'hello_world', to: 'hello_world#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#index'


  devise_for :users, controllers: { registrations: 'registrations' }

  resources :cookers
  resources :eaters

  get "/eater" => "eaters#show"    #redirects url to show
  get "/cooker" => "cookers#show"  #redirects url to show


  #resources :users

end

app/views/partials/_cooker.html.erb
<div id="cooker-profile">

    <div class"nested-profile-top">
      <div class="cook-photo-id">
        <div class="cook-photo"><img src="<%= cooker.profile_photo %>" class="cooker-img"></div><br/>
        <div class="cook-name"><%= User.find_by_id(cooker.user_id).username%></div>
      </div>
      <div class="cook-stats">
        <div><strong>Price </strong>  <%= cooker.price_per_week %></div>
        <div><strong>Neighborhood: </strong>  <%= cooker.neighborhood %></div>
        <div><strong>Delivery Available? </strong>  <%= cooker.delivery_available == true ? "Yes" : "No" %></div>
        <div><strong>Specialty Diet: </strong>  <%= cooker.dietary_options %></div>
        <div class="about-cook">
          <%= cooker.food_description %>
        </div>
      </div>
    </div>


    <div>
      <%= form_for (current_user.eater), url: eater_path(current_user.eater.id), method: :patch do |f| %>
      <%= f.hidden_field :cooker_id, :value => cooker.id %>
      <%= f.submit "Subscribe", class:'button' %>
      <% end %>
    </div>

</div>

<script>
$(".btn-primary").click(function() {
  swal({title:'Subscribed To New Cook',
  input: ''
  });
});
</script>

balls

app/views/partials/_cooker_home.html.erb
  <div class="wrapper-cook-profile">
    <div class"nested-profile-top">

      <div class="cook-photo-id">
        <div class="cook-photo"><img src="<%= cooker.profile_photo %>" class="cooker-img"></div><br/>
        <div class="cook-name"><%= User.find_by_id(cooker.user_id).username%></div> 
      </div>

      <div class="cook-stats">
        <br/>Price Per Week (USD) :  <%= cooker.price_per_week %>
        <br/>Neighborhood :  <%= cooker.neighborhood %>
        <br/>Delivery Available? : <%= cooker.delivery_available == true ? "Yes" : "No" %>
        <br/>Specialty Diets :  <%= cooker.dietary_options %>  
      </div>
    </div>
    <div class="about-cook">
        <%= cooker.food_description %>
    </div>
    <div class="subscribe-button-field">
      <%= link_to "edit", edit_cooker_path(current_user.cooker.id), method: :get, class:"btn btn-info subscribe-button" %>
    </div>
  </div>
            
 
          

app/views/partials/_curr_cook.html.erb
<div class='current-cook-container'>
  <div>
      <img src="<%= current_user.eater.cooker.profile_photo%>" class="cooker-img">
      <h4 align="center"><%= current_user.eater.cooker.user.username%></h4>
  </div>
  <div align="center"><a onclick="myFunction()">Cook Details</a></div>
  <div id="curr-cook-details">
          <div><strong>EMAIL:</strong> <%=current_user.eater.cooker.user.email%></div>
          <div><strong>PHONE:</strong> <%=current_user.eater.cooker.user.phone_number %></div>
          </br>
          <div><strong>FOOD DESCRIPTION</strong></div>
          <div><%= current_user.eater.cooker.food_description%></div>
  </div>
</div>


<script>
function myFunction() {
  var x = document.getElementById("curr-cook-details");
  if (x.style.display === "none") {
    x.style.display = "block";
    } else {
      x.style.display = "none";
    }
  }
</script>

app/views/partials/_eater_info.html.erb
<%=if current_user.eater.cooker_id %>
<%=p current_user.eater.cooker.user.username %>
<%= else %>
<%=p "You are not currently subscribed to a cook"%>
<% end %>
<% end %>

app/views/partials/_nav.html.erb
  <nav class="navbar navbar-dark fixed-top">
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#collapseNav'>
      &#9776;
    </button>
      <div class="collapse navbar-toggleable-xl" id='collapseNav'>
          <ul class="dropdown-nav">
            <li><%= link_to "Account", edit_user_registration_path, method: :get, class: 'nav-option' %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-option' %></li>
          </ul>
      </div>

  </nav>